import type { Enemy } from '@/types'

export const ENEMIES: Enemy[] = [
  // ── Comuns ──────────────────────────────────────────────────
  {
    id: 'sombra_errante',
    name: 'Sombra Errante',
    description: 'Uma entidade das Sombras Externas, sem forma definida.',
    portraitImage: '/images/enemies/sombra_errante.png',
    habilidade: 6,
    energia: 8,
    damage: { count: 1, faces: 4, bonus: 0 },
    fleeable: true,
    goldReward: 5,
    bestiaryFlavor: 'A primeira vez que você matou uma, quase não pareceu morte. Era mais como apagar uma vela.',
  },
  {
    id: 'sombra_bosque',
    name: 'Sombra do Bosque',
    description: 'Sombra que assumiu a forma de um cervo. Habita Mirthwood corrompida.',
    portraitImage: '/images/enemies/sombra_bosque.png',
    habilidade: 8,
    energia: 14,
    damage: { count: 1, faces: 6, bonus: 1 },
    fleeable: false,
    goldReward: 8,
    itemDropId: 'erva_sombra',
    dropChance: 0.5,
    bestiaryFlavor: 'Os chifres eram de fumaça, mas machucavam como ferro.',
  },
  {
    id: 'lobo_corrompido',
    name: 'Lobo Corrompido',
    description: 'Lobo da floresta infectado pela sombra de Korvath.',
    portraitImage: '/images/enemies/lobo_corrompido.png',
    habilidade: 8,
    energia: 9,
    damage: { count: 1, faces: 6, bonus: 0 },
    fleeable: true,
    goldReward: 0,
    bestiaryFlavor: 'Seus olhos tinham cor de fumaça. Nenhum lobo natural tem olhos assim.',
  },
  {
    id: 'bandido_estrada',
    name: 'Bandido',
    description: 'Ladrão de estrada oportunista.',
    portraitImage: '/images/enemies/bandido_estrada.png',
    habilidade: 7,
    energia: 12,
    damage: { count: 1, faces: 4, bonus: 1 },
    fleeable: false,
    goldReward: 15,
    bestiaryFlavor: 'Não era malvado. Era com fome. Não é a mesma coisa, mas também não é diferente.',
  },
  {
    id: 'assassino_guilda',
    name: 'Assassino da Guilda',
    description: 'Membro treinado da Guilda da Adaga Quieta.',
    portraitImage: '/images/enemies/assassino_guilda.png',
    habilidade: 9,
    energia: 11,
    damage: { count: 1, faces: 6, bonus: 1 },
    fleeable: true,
    goldReward: 20,
    itemDropId: 'po_cegueira',
    dropChance: 0.5,
    bestiaryFlavor: 'Qualquer um pode aprender a matar. A Guilda ensina a matar sem ser lembrado.',
  },
  {
    id: 'assassino_guilda_fraco',
    name: 'Assassino da Guilda (ferido)',
    description: 'Membro da Guilda em desvantagem.',
    portraitImage: '/images/enemies/assassino_guilda.png',
    habilidade: 9,
    energia: 7,
    damage: { count: 1, faces: 6, bonus: 1 },
    fleeable: true,
    goldReward: 10,
    bestiaryFlavor: 'Qualquer um pode aprender a matar. A Guilda ensina a matar sem ser lembrado.',
  },
  {
    id: 'esqueleto_anao',
    name: 'Esqueleto Anão',
    description: 'Guardião morto-vivo de Karn-Tuhl. Armadura enferrujada, determinação intacta.',
    portraitImage: '/images/enemies/esqueleto_anao.png',
    habilidade: 7,
    energia: 8,
    damage: { count: 1, faces: 6, bonus: 0 },
    fleeable: false,
    goldReward: 0,
    bestiaryFlavor: 'Eles ainda guardam. Não sabem que não há mais nada para guardar.',
  },
  {
    id: 'esqueleto_anao_duplo',
    name: 'Esqueletos Anões',
    description: 'Dois guardiões mortos-vivos agindo em conjunto.',
    portraitImage: '/images/enemies/esqueleto_anao.png',
    habilidade: 7,
    energia: 14,
    damage: { count: 1, faces: 6, bonus: 1 },
    fleeable: false,
    goldReward: 0,
    bestiaryFlavor: 'Eles ainda guardam. Não sabem que não há mais nada para guardar.',
  },
  {
    id: 'cavaleiro_sombrio',
    name: 'Cavaleiro Sombrio',
    description: 'Armadura vazia animada pela vontade de Vorthun.',
    portraitImage: '/images/enemies/cavaleiro_sombrio.png',
    habilidade: 9,
    energia: 14,
    damage: { count: 1, faces: 6, bonus: 2 },
    fleeable: false,
    goldReward: 0,
    bestiaryFlavor: 'Não havia nada dentro da armadura. Isso tornava o golpe mais assustador, não menos.',
  },

  // ── Chefes ──────────────────────────────────────────────────
  {
    id: 'combat_korvath',
    name: 'Druida Korvath',
    description: 'Druida corrompido pela Sombra. Antlers pretos crescem do crânio.',
    portraitImage: '/images/scenes/korvath.png',
    habilidade: 9,
    energia: 22,
    damage: { count: 1, faces: 6, bonus: 2 },
    fleeable: false,
    goldReward: 0,
    bestiaryFlavor: 'Ele não queria o que se tornou. Isso não tornou o golpe mais fácil.',
  },
  {
    id: 'combat_senhora_sombria',
    name: 'Senhora Sombria da Guilda',
    description: 'Aelin Faro, mestre da Guilda. Serve a Vorthun.',
    portraitImage: '/images/scenes/senhora_sombria.png',
    habilidade: 10,
    energia: 20,
    damage: { count: 1, faces: 6, bonus: 2 },
    fleeable: false,
    goldReward: 0,
    bestiaryFlavor: 'O sorriso dela era de quem já venceu antes do combate começar. Desta vez, não.',
  },
  {
    id: 'combat_forja_animada',
    name: 'Forja Animada',
    description: 'Conjunto de armaduras anãs animadas pela magia dos guardiões mortos.',
    portraitImage: '/images/enemies/combat_forja_animada.png',
    habilidade: 8,
    energia: 26,
    damage: { count: 1, faces: 8, bonus: 0 },
    fleeable: false,
    goldReward: 0,
    bestiaryFlavor: 'Não era um golem. Era uma decisão feita de ferro.',
  },
  {
    id: 'combat_algoz',
    name: 'Algoz de Vorthun',
    description: 'Tenente do Sombrio Coroado. Capuz de sombra, cutelo do tamanho de um peito.',
    portraitImage: '/images/enemies/combat_algoz.png',
    habilidade: 10,
    energia: 24,
    damage: { count: 2, faces: 4, bonus: 0 },
    fleeable: false,
    goldReward: 25,
    bestiaryFlavor: 'Ele não falou uma palavra. Era mais respeitoso do que a maioria.',
  },
  {
    id: 'combat_vorthun',
    name: 'Vorthun, o Sombrio Coroado',
    description: 'O lich. Armadura negra rachada, coroa fundida ao crânio, muitas vozes em uma.',
    portraitImage: '/images/scenes/vorthun_throne.png',
    habilidade: 11,
    energia: 30,
    damage: { count: 1, faces: 8, bonus: 2 },
    fleeable: false,
    goldReward: 0,
    bestiaryFlavor: 'Era um homem uma vez. Isso não muda nada. Talvez mude tudo.',
  },
  {
    id: 'combat_vorthun_traicao',
    name: 'Vorthun (Traído)',
    description: 'Vorthun sabe que você o enganou. Mais rápido. Mais frio.',
    portraitImage: '/images/scenes/vorthun_throne.png',
    habilidade: 11,
    energia: 26,
    damage: { count: 1, faces: 6, bonus: 3 },
    fleeable: false,
    goldReward: 0,
    bestiaryFlavor: 'Já foi enganado por si mesmo. Não perdoa um segundo.',
  },
]

export const ENEMY_MAP = new Map(ENEMIES.map(e => [e.id, e]))

export function getEnemy(id: string): Enemy | undefined {
  return ENEMY_MAP.get(id)
}
