import type { Item } from '@/types'

export const ITEMS: Item[] = [
  // ── Consumíveis ─────────────────────────────────────────────
  {
    id: 'pocao_cura_menor',
    name: 'Poção de Cura Menor',
    description: 'Um frasco de líquido âmbar. Restaura um pouco de energia.',
    type: 'consumable',
    effect: { kind: 'heal', amount: 6 },
    stackable: true,
    goldValue: 12,
    usableInCombat: true,
    usableOutOfCombat: true,
  },
  {
    id: 'pocao_cura',
    name: 'Poção de Cura',
    description: 'Um frasco de líquido rubro. Restaura energia considerável.',
    type: 'consumable',
    effect: { kind: 'heal', amount: 12 },
    stackable: true,
    goldValue: 25,
    usableInCombat: true,
    usableOutOfCombat: true,
  },
  {
    id: 'pocao_sorte',
    name: 'Poção de Sorte',
    description: 'Líquido dourado com partículas brilhantes. Restaura Sorte.',
    type: 'consumable',
    effect: { kind: 'restoreSorte', amount: 2 },
    stackable: true,
    goldValue: 30,
    usableInCombat: false,
    usableOutOfCombat: true,
  },
  {
    id: 'po_cegueira',
    name: 'Pó da Cegueira',
    description: 'Pó irritante. Faz o inimigo errar o próximo ataque.',
    type: 'consumable',
    effect: { kind: 'special', tag: 'blind_enemy' },
    stackable: true,
    goldValue: 15,
    usableInCombat: true,
    usableOutOfCombat: false,
  },
  {
    id: 'erva_sombra',
    name: 'Erva da Sombra',
    description: 'Erva rara da Floresta de Mirthwood. Aguça os sentidos.',
    type: 'consumable',
    effect: { kind: 'tempBuff', stat: 'habilidade', amount: 2, duration: 3 },
    stackable: true,
    goldValue: 18,
    usableInCombat: true,
    usableOutOfCombat: false,
  },
  {
    id: 'carne_seca',
    name: 'Carne Seca',
    description: 'Ração de viagem. Restaura um pouco de energia.',
    type: 'consumable',
    effect: { kind: 'heal', amount: 3 },
    stackable: true,
    goldValue: 3,
    usableInCombat: false,
    usableOutOfCombat: true,
  },
  {
    id: 'chifre_lunar',
    name: 'Chifre Lunar',
    description: 'Um chifre de veado branco. Não tem utilidade prática.',
    type: 'misc',
    effect: { kind: 'special', tag: 'sell_only' },
    stackable: false,
    goldValue: 25,
    usableInCombat: false,
    usableOutOfCombat: false,
  },
  {
    id: 'martelo_de_brasa',
    name: 'Martelo de Brasa',
    description: 'Martelo anão que ainda guarda calor. Canaliza força em combate. 3 usos.',
    type: 'consumable',
    effect: { kind: 'damageBoost', amount: 2, duration: 1 },
    stackable: false,
    goldValue: 0,
    usableInCombat: true,
    usableOutOfCombat: false,
  },
  {
    id: 'pergaminho_de_brasa',
    name: 'Pergaminho de Brasa',
    description: 'Runa anã. Fortalece o próximo ataque. Uso único.',
    type: 'consumable',
    effect: { kind: 'damageBoost', amount: 3, duration: 1 },
    stackable: true,
    goldValue: 0,
    usableInCombat: true,
    usableOutOfCombat: false,
  },
  {
    id: 'pergaminho_de_raiz',
    name: 'Pergaminho de Raiz',
    description: 'Runa druídica. Restaura Sorte em combate. Uso único.',
    type: 'consumable',
    effect: { kind: 'restoreSorte', amount: 3 },
    stackable: true,
    goldValue: 30,
    usableInCombat: true,
    usableOutOfCombat: false,
  },
  {
    id: 'lamina_afiada',
    name: 'Lâmina Afiada',
    description: 'Lâmina recém-afiada. +1 dano por 5 rounds. Uso único.',
    type: 'consumable',
    effect: { kind: 'damageBoost', amount: 1, duration: 5 },
    stackable: true,
    goldValue: 30,
    usableInCombat: true,
    usableOutOfCombat: false,
  },

  // ── Equipamentos ─────────────────────────────────────────────
  {
    id: 'manopla_sombria',
    name: 'Manopla Sombria',
    description: 'Manopla do Algoz. Aumenta a destreza em combate.',
    type: 'equipment',
    effect: { kind: 'special', tag: 'equip' },
    stackable: false,
    goldValue: 0,
    usableInCombat: false,
    usableOutOfCombat: false,
    equipmentBonus: { habilidade: 1 },
  },
  {
    id: 'amuleto_arvendel',
    name: 'Amuleto de Arvendel',
    description: 'Amuleto do sábio. Aumenta o limite máximo de Sorte.',
    type: 'equipment',
    effect: { kind: 'special', tag: 'equip' },
    stackable: false,
    goldValue: 0,
    usableInCombat: false,
    usableOutOfCombat: false,
    equipmentBonus: { sorteMax: 1 },
  },
  {
    id: 'botas_silenciosas',
    name: 'Botas Silenciosas',
    description: 'Botas cobertas de couro macio. +1 em Furtividade.',
    type: 'equipment',
    effect: { kind: 'special', tag: 'equip' },
    stackable: false,
    goldValue: 80,
    usableInCombat: false,
    usableOutOfCombat: false,
    equipmentBonus: { furtividade: 1 },
  },
  {
    id: 'anel_de_brom',
    name: 'Anel de Brom',
    description: 'Anel pessoal do ferreiro Brom Pedraferro. +1 Sorte máxima.',
    type: 'equipment',
    effect: { kind: 'special', tag: 'equip' },
    stackable: false,
    goldValue: 0,
    usableInCombat: false,
    usableOutOfCombat: false,
    equipmentBonus: { sorteMax: 1 },
  },
]

export const ITEM_MAP = new Map(ITEMS.map(i => [i.id, i]))

export function getItem(id: string): Item | undefined {
  return ITEM_MAP.get(id)
}
